### PR TITLE
285 - Add a fix to updatePagingInfo

### LINKED ISSUE #285: Datagrid: updatePagingInfo is not defined when running outside of angular
**Describe the bug**
When trying to set the page of the data grid it is unable to find the function when running outside of angular.

**To Reproduce**
try running this.datagrid.updatePagingInfo({activePage: 2});
https://github.com/infor-design/enterprise-ng/blob/cdbedcb485ad466b097aa06879a59e25ec6b3483/projects/ids-enterprise-ng/src/lib/datagrid/soho-datagrid.component.ts#L1204

**Expected behavior**
the page should be updated to the second page

**Version**
- ids-enterprise-ng:  v4.12.1

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Since some pager refactor/changes we moved the updatePagingInfo function to the pager API. this caused the one wiered here on datagrid to not work. I fixed this and added a test page.

Also updated master to the latest dev version

**Related github/jira issue (required)**:
Fixes #285 

**Steps necessary to review your pull request (required)**:
- pull this
- npm i && npm run build && npm run start
- go to page http://localhost:4200/ids-enterprise-ng-demo/datagrid-paging-service
- click "go to page 2" and it should set the pager to page 2

### CODE REVIEW

File: projects/ids-enterprise-ng/src/lib/datagrid/soho-datagrid.d.ts [hunk 1]
```diff
@@ -933,6 +933,7 @@ interface SohoDataGridStatic {
 
   /** Reference to pager. */
   pager: SohoPagerStatic;
```
Comment (fitzorama) [inline projects/ids-enterprise-ng/src/lib/datagrid/soho-datagrid.d.ts:935]: does this become deprecated then?

Comment (tmcconechy) [reply projects/ids-enterprise-ng/src/lib/datagrid/soho-datagrid.d.ts:935]: Sure we call it pagerAPI internally so i copied that over. I wasnt really sure if this was accessed this way or not so i left both. But we can deprecate it ?

Comment (fitzorama) [reply projects/ids-enterprise-ng/src/lib/datagrid/soho-datagrid.d.ts:935]: good question; i was just asking because of two properties that had the same type

Comment (tmcconechy) [reply projects/ids-enterprise-ng/src/lib/datagrid/soho-datagrid.d.ts:935]: I'll just mark pager as deprecated in favor of pagerAPI as we have API in a few places

Comment (tmcconechy) [reply projects/ids-enterprise-ng/src/lib/datagrid/soho-datagrid.d.ts:935]: Soon...when im done another PR
