### PR TITLE
stand alone pager optimizations

### LINKED ISSUE #843: Calling enablePager buttons in soho-standalone-pager rebuilds the entire pager bar
**Describe the bug**
Calling enablePager buttons in soho-standalone-pager rebuilds the entire pager bar.

**To Reproduce**
1. go to 'stand alone pager example'
2. Click on enable first/last/prev/next button and note pager.updated is called each time.

see ngAfterViewChecked function in soho-standalone-pager
```
  ngAfterViewChecked() {
    if (this.pager && this.updateRequired) {
      this.pager.updated(this.options);
      this.updateRequired = false;
    }
  }
````

**Expected behavior**
enable buttons should message the enableButtons function directly in pager.js

**Version**
- ids-enterprise-ng: v7.2

### PR DESCRIPTION
**Pull request by pwpatton**
The standalone-pager was causing the EP pager component to rebuild on each enable/show of a pager button. 

**Related github/jira issue (required)**:
Closes #843 

**Steps necessary to review your pull request (required)**:
- open stand alone pager example http://localhost:4200/ids-enterprise-ng-demo/pager-standalone
- set a breakpoint in sohoxi.js pager renderButton
- click each show/hide pager button on example page
- renderButton should not be called anymore on these operations.

### CODE REVIEW

File: projects/ids-enterprise-ng/src/lib/pager/soho-standalone-pager.component.ts [hunk 1]
```diff
@@ -31,47 +31,83 @@ export class SohoStandalonePagerComponent implements AfterViewInit, AfterViewChe
 
   @Input() set showFirstButton(showFirstButton: boolean) {
     this.options.showFirstButton = showFirstButton;
-    this.updateRequired = !!this.pager;
+    if (this.pager) {
+      this.pager.showButton('first', showFirstButton);
+    } else {
+      this.updateRequired = !!this.pager;
```
Comment (nbcp) [inline projects/ids-enterprise-ng/src/lib/pager/soho-standalone-pager.component.ts:37]: A bit confused with setting `this.updateRequired` to `false` when the pager is not built yet. Shouldn't it be `this.updateRequired = true;` since we'd want to update the pager via AfterViewCheck once it's built?

Comment (pwpatton) [reply projects/ids-enterprise-ng/src/lib/pager/soho-standalone-pager.component.ts:37]: @nbcp yes, I think that is more clear. I'll update.
